"""
Django settings for the PrESTO project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

"""
Copyright (c) 2019 Delft University of Technology

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETTINGS_DIR = os.path.dirname(os.path.abspath(__file__))

# directory for daily log files written to by log_message() in utils.py
LOG_DIR = os.environ.get('LOG_DIR', os.path.join(BASE_DIR, 'log'))

# needed for workaround when opening uploaded documents in download.py
LEADING_SLASH = os.environ.get('LEADING_SLASH', '')

#if not set through environment ( docker) then user False
USE_SAML_STR = os.environ.get('USE_SAML', 'False')
USE_SAML = USE_SAML_STR == 'True'

if USE_SAML is True:
    import saml2
    from saml2 import BINDING_HTTP_REDIRECT, BINDING_URI
    from saml2 import BINDING_HTTP_ARTIFACT
    from saml2 import BINDING_HTTP_POST
    from saml2 import BINDING_SOAP
    from saml2.saml import NAME_FORMAT_URI
    from saml2.saml import NAMEID_FORMAT_TRANSIENT
    from saml2.saml import NAMEID_FORMAT_PERSISTENT

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$secret_key_to_be_replaced_by_your_own_key_string$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG_STR = os.environ.get('DEBUG', 'True')
DEBUG = DEBUG_STR == 'True'

# NOTE: replace the constants below by your own:
DOMAIN_NAME = 'your_domain.name'
HOST_NAME = 'presto.your_domain.name'
ADMIN_NAME = 'Your Name'
ADMIN_MAIL = 'your_mail@your_domain.name'


ALLOWED_HOSTS = ['127.0.0.1', HOST_NAME]

# if DEBUG is false, send mail to admin when error 500 occurs
# NOTE: also adapt the constants below to your mail and server configurations:
admins = os.environ.get('ADMINS', "(('%s', '%s'),)" % (ADMIN_NAME, ADMIN_MAIL))
ADMINS = eval(admins)
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', 'no-reply@your_domain.name')
EMAIL_FROM = u'Presto Administrator'
ERROR_EMAIL = ''
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'your.email.host'
EMAIL_HOST_USER = 'noreply@your_domain.name'
EMAIL_PORT = 25

# Application definition
if USE_SAML is True:    
    INSTALLED_APPS = [
        'presto.apps.PrestoConfig',

        'django.contrib.admin.apps.SimpleAdminConfig',    

        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'djangosaml2',
    ]
else:
    INSTALLED_APPS = [
        'presto.apps.PrestoConfig',

        'django.contrib.admin',  # only difference if USE_SAML is False
        
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
    ]    
    
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'presto-project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR + '/presto/templates/presto/',
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'string_if_invalid': '%s',  # REMOVE THIS AFTER DEBUGGING!!
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'presto-project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# NOTE: ensure that on your server the required environment variables are set

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'presto'),
        'USER': os.environ.get('DB_USER', 'presto'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'presto'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': 'SET storage_engine=InnoDB;SET sql_mode="STRICT_TRANS_TABLES"'
        }
    },
}

# NOTE: At TU Delft, server authentication occurs via SimpleSAML.
#       You can override this by setting USE_SAML to False, or by altogether
#       removing the SAML-related code in this settings file.
# NOTE: If you wish to use SAML, you still need to modify the TU Delft related
#       string constants to match your own SAML configuration.

if USE_SAML is False:
    AUTHENTICATION_BACKENDS = (
        'django.contrib.auth.backends.ModelBackend',
    )
    LOGIN_URL = '/admin/login/'
    
    # used only in demo-login view
    DEMO_USR_BACKEND = 'django.contrib.auth.backends.ModelBackend'

else: 
    AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    #'djangosaml2.backends.Saml2Backend',
    'presto-project.backends.MySaml2Backend',
    )

    # used only in the demo-login view, as demo-users need not have a SAML login name + password
    DEMO_USR_BACKEND = 'presto-project.backends.MySaml2Backend'  # 'djangosaml2.backends.Saml2Backend'

    # -----SAML Settings -----
    LOGIN_URL = '/saml2/login/'
    LOGOUT_URL = '/saml2/logout/'
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True
    
    SAML_CONFIG = {
        # full path to the xmlsec1 binary programm
        'xmlsec_binary': '/usr/bin/xmlsec1',
      
        # your entity id, usually your subdomain plus the url to the metadata view
        'entityid': 'https://presto.tudelft.nl',
      
        # directory with attribute mapping
        'attribute_map_dir': os.path.join(BASE_DIR, 'saml/attribute-maps'),
        'allow_unknown_attributes': False,
      
        # this block states what services we provide
        'service': {
            # we are just a lonely SP
            'sp': {
                'name': 'Software',
                'name_id_format': NAMEID_FORMAT_PERSISTENT,
                'endpoints': {
                    # url and binding to the assetion consumer service view
                    # do not change the binding or service name
                    'assertion_consumer_service': [
                        ('https://presto.tudelft.nl/saml2/acs/',
                         BINDING_HTTP_POST),
                    ],
                    # url and binding to the single logout service view
                    # do not change the binding or service name
                    'single_logout_service': [
                        ('https://presto.tudelft.nl/saml2/ls/',
                         BINDING_HTTP_REDIRECT),
                    ],
                },
      
                # attributes that this project need to identify a user
                'required_attributes': ['uid', 'sn', 'mail'],
                # attributes that may be useful to have but not required
                #'optional_attributes': ['eduPersonAffiliation'],
                
                'authn_requests_signed': True,
                'want_assertions_signed': False,
                'want_responses_signed': True,
      
                'allow_unknown_attributes': False,
            },
        },
      
        # where the remote metadata is stored
        'metadata': {
            'local': [os.path.join(BASE_DIR, 'saml/metadata/metadata.xml')],
        },
      
        # set to 1 to output debugging information
        'debug': 1,
      
        # certificate
        'key_file': os.path.join(BASE_DIR, 'saml/cert/saml.key'),  # private part
        'cert_file': os.path.join(BASE_DIR, 'saml/cert/saml.crt'),  # public part
      
        # own metadata settings
        # NOTE: these must be adapted to your own situation!
        'contact_person': [
            {'given_name': 'Your_first_name',
             'sur_name': 'Your_last_name',
             'company': 'TU Delft',
             'email_address': 'your_mail_address',
             'contact_type': 'technical'},
        ],
        # you can set multilanguage information here
        'organization': {
            'name': [('TU Delft', 'nl'), ('University of Technology', 'en')],
            'display_name': [('TU Delft', 'nl'), ('TU Delft', 'en')],
            'url': [('http://www.tudelft.nl', 'nl'), ('http://www.tudelft.nl', 'en')],
        },
        # 'valid_for': 24,  # how long is our metadata valid
    }

    SAML_ATTRIBUTE_MAPPING = {
        'urn:mace:dir:attribute-def:uid': ('username',),
        'mail': ('email',),
        'sn': ('last_name',),
        'givenName': ('first_name',),
    }
     
    SAML_CREATE_UNKNOWN_USER = True
    SAML_DJANGO_USER_MAIN_ATTRIBUTE = 'username'

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Amsterdam'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = 'static/'
MEDIA_ROOT = '/upload/'

# NOTE: you must change the Presto URL to your own!
PRESTO_URL = 'https://presto.tudelft.nl'

# path to directory for images
IMAGE_DIR = os.path.join(BASE_DIR, 'static', 'presto', 'images')

# path to directory for fonts (referred to in progress.py)
FONT_DIR = os.path.join(BASE_DIR, 'static', 'presto', 'fonts')

# directory for badge icon images -- NOT in static, as this image should not be public
BADGE_DIR = os.path.join(BASE_DIR, 'badge_icons')

# parameters for encrypting badges
# NOTE: keep these secret for production version!
BADGE_SALT = '$replace_this_by_a_random_ascii_string_of_about_this_length$'
BADGE_ITERATIONS = 12345  # replace by some other number >> 10 thousand

# username of "dummy user" that can enroll multiple times in a course
# NOTE: only this demo_user can have multiple sessions, each focusing on a single "dummy"
DEMO_USER_NAME = 'prestodemo'

# allow up to 2 MB per upload file
MAX_UPLOAD_SIZE = 2.0

# mail address for Picture Queue functionality
# NOTE: keep these secret for production version!
PICTURE_QUEUE_MAIL = 'a_valid_mail_address'
PICTURE_QUEUE_SERVER = 'pop_server_name_for_this_address'
PICTURE_QUEUE_PWD = 'password_for_this_mail_account'

# use local settings file to override Linux server settings
try:
    exec open(os.path.join(SETTINGS_DIR, 'settings_local.py')) in globals()
    print "Loaded local configuration"
except IOError as e:
    # print "Did not load any local configuration"
    pass

