# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presto', '0002_auto_20170926_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_qualified', models.DateTimeField(default=django.utils.timezone.now)),
                ('estafette_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presto.EstafetteLeg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appeal',
            name='referee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='presto.Referee'),
            preserve_default=False,
        ),
    ]
