# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0007_auto_20171016_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presto.Referee'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presto.PeerReview'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presto.EstafetteCase'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='clone_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='original_assignment', to='presto.Assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='leg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presto.EstafetteLeg'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presto.Participant'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preceding_assignment', to='presto.Assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='successor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='succeeding_assignment', to='presto.Assignment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='presto.Language'),
        ),
        migrations.AlterField(
            model_name='course',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseestafette',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presto.Course'),
        ),
        migrations.AlterField(
            model_name='courseestafette',
            name='questionnaire_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presto.QuestionnaireTemplate'),
        ),
        migrations.AlterField(
            model_name='estafette',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='e_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estafette',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estafettecase',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ec_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estafettecase',
            name='estafette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presto.Estafette'),
        ),
        migrations.AlterField(
            model_name='estafettecase',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ec_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estafettecase',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presto.CaseUpload'),
        ),
        migrations.AlterField(
            model_name='estafetteleg',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='el_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estafetteleg',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='el_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estafetteleg',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='estafetteleg',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presto.EstafetteTemplate'),
        ),
        migrations.AlterField(
            model_name='estafettetemplate',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='est_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estafettetemplate',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='est_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='estafette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presto.CourseEstafette'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presto.CourseStudent'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presto.Language'),
        ),
        migrations.AlterField(
            model_name='questionnairetemplate',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evt_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionnairetemplate',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evt_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='active_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presto.Role'),
        ),
    ]
