# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0011_auto_20171121_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressBin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_nr', models.IntegerField(blank=True, default=0)),
                ('bin_nr', models.IntegerField(blank=True, default=0)),
                ('bin_cnt', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
