# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0012_progressbin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressBin',
        ),
    ]
