# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 15:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0013_delete_progressbin'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='time_started',
            field=models.DateTimeField(default=datetime.datetime(2000, 12, 31, 23, 0, tzinfo=utc)),
        ),
    ]
