# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0014_participant_time_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerreview',
            name='final_review_index',
            field=models.IntegerField(default=0),
        ),
    ]
