# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0016_auto_20171202_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseestafette',
            name='with_review_clips',
            field=models.BooleanField(default=False),
        ),
    ]
