# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0017_courseestafette_with_review_clips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estafetteleg',
            old_name='min_minutes',
            new_name='min_reject_minutes',
        ),
        migrations.AddField(
            model_name='estafetteleg',
            name='review_model_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
