# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0018_auto_20171220_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='estafetteleg',
            name='min_review_minutes',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='estafetteleg',
            name='min_upload_minutes',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='estafetteleg',
            name='min_reject_minutes',
            field=models.IntegerField(default=20),
        ),
    ]
