# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0019_auto_20171220_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estafetteleg',
            name='min_reject_minutes',
        ),
        migrations.AlterField(
            model_name='estafetteleg',
            name='min_review_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
