# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 07:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0020_auto_20171221_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='time_scanned',
            field=models.DateTimeField(default=datetime.datetime(2000, 12, 31, 23, 0, tzinfo=utc)),
        ),
    ]
