# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0022_assignment_scan_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseestafette',
            name='actual_rules',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='estafettetemplate',
            name='default_rules',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='step_not_performed',
            field=models.BooleanField(default=False),
        ),
    ]
