# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0024_legvideo_objection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestoBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_file_name', models.CharField(max_length=32)),
                ('levels', models.IntegerField(default=0)),
                ('attained_level', models.IntegerField(default=0)),
                ('time_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_last_rendered', models.DateTimeField(default=datetime.datetime(2000, 12, 31, 23, 0, tzinfo=utc))),
                ('rendering_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='badge_color',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseestafette',
            name='with_badges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseestafette',
            name='with_referees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estafette',
            name='badge_shade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prestobadge',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presto.Course'),
        ),
        migrations.AddField(
            model_name='prestobadge',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presto.Participant'),
        ),
        migrations.AddField(
            model_name='prestobadge',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presto.Referee'),
        ),
    ]
