# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0025_auto_20180226_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(default='(no key)', max_length=64),
        ),
    ]
