# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 14:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import presto.models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0027_auto_20180228_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterOfAknowledgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('authentication_code', models.CharField(default=presto.models.random_hex32, max_length=32)),
                ('step_list', models.CharField(blank=True, default='', max_length=32)),
                ('appeal_case_count', models.IntegerField(default=0)),
                ('extra_hours', models.IntegerField(default=0)),
                ('average_appreciation', models.FloatField(default=0)),
                ('time_last_rendered', models.DateTimeField(default=datetime.datetime(2000, 12, 31, 23, 0, tzinfo=utc))),
                ('rendering_count', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presto.Course')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presto.Referee')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='is_edx_user',
            field=models.BooleanField(default=False),
        ),
    ]
