# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0030_auto_20180323_1102'),
    ]

    operations = [
        migrations.RenameModel('LetterOfAknowledgement', 'LetterOfAcknowledgement')
    ]
