# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0031_auto_20180323_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestobadge',
            name='icon_file_name',
        ),
    ]
