# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0032_remove_prestobadge_icon_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='estafette',
            name='hours_per_appeal',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='letterofacknowledgement',
            name='time_first_case',
            field=models.DateTimeField(default=datetime.datetime(2000, 12, 31, 23, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='letterofacknowledgement',
            name='time_last_case',
            field=models.DateTimeField(default=datetime.datetime(2000, 12, 31, 23, 0, tzinfo=utc)),
        ),
    ]
