# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 05:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presto', '0034_auto_20180324_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('instruction', models.TextField(blank=True, default='')),
                ('word_count', models.IntegerField(default=0)),
                ('appraisal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('style', models.CharField(max_length=64)),
                ('options', models.ManyToManyField(to='presto.AppraisalOption')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='suffix',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='courseestafette',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estafettetemplate',
            name='editors',
            field=models.ManyToManyField(related_name='est_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnairetemplate',
            name='editors',
            field=models.ManyToManyField(related_name='evt_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estafettetemplate',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='est_last_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionnairetemplate',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evt_last_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estafetteleg',
            name='review_items',
            field=models.ManyToManyField(to='presto.Item'),
        ),
    ]
