# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0035_auto_20180327_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseestafette',
            name='review_deadline',
            field=models.DateTimeField(default=datetime.datetime(2000, 12, 31, 23, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='questionnairetemplate',
            name='items',
            field=models.ManyToManyField(to='presto.Item'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
