# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 06:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presto', '0036_auto_20180327_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='estafette',
            name='editors',
            field=models.ManyToManyField(related_name='e_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estafette',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_last_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
