# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0037_auto_20180327_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
