# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0038_auto_20180327_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisaloption',
            name='color',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='courseestafette',
            name='scoring_system',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='model_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
