# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-23 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0039_auto_20180328_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='model_text',
        ),
        migrations.AddField(
            model_name='item',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='estafetteleg',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presto.EstafetteTemplate'),
        ),
        migrations.AlterField(
            model_name='item',
            name='appraisal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presto.ItemAppraisal'),
        ),
        migrations.AlterField(
            model_name='itemappraisal',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
