# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-28 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0042_auto_20180724_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='itemappraisal',
            name='options',
            field=models.ManyToManyField(blank=True, to='presto.AppraisalOption'),
        ),
    ]
