# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0043_auto_20180728_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='particulars',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
