# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-03 06:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0044_auto_20180730_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estafette',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='e_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estafettetemplate',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='est_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionnairetemplate',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='evt_editors', to=settings.AUTH_USER_MODEL),
        ),
    ]
