# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-04 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0046_auto_20180804_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseupload',
            name='original_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseestafette',
            name='high_grade_range',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='courseestafette',
            name='high_score_range',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='courseestafette',
            name='low_grade_range',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='courseestafette',
            name='low_score_range',
            field=models.FloatField(default=-1000),
        ),
    ]
