# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0048_estafetteleg_learning_objectives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='suffix',
        ),
    ]
