# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import presto.models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0049_remove_course_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=presto.models.course_pq_dir)),
                ('time_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presto.CourseStudent')),
            ],
        ),
        migrations.AlterField(
            model_name='estafette',
            name='upload_dir',
            field=models.CharField(default=presto.models.relay_dir_name, max_length=32, unique=True),
        ),
    ]
