# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import presto.models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0051_coursestudent_picture_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='picture_dir',
            field=models.CharField(default=presto.models.pq_dir_name, max_length=35),
        ),
    ]
