# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0052_auto_20180815_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestudent',
            name='picture_dir',
        ),
    ]
