# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0053_remove_coursestudent_picture_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture_dir',
            field=models.CharField(default='xxx', max_length=35),
        ),
    ]
