# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-16 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0055_auto_20180815_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuepicture',
            name='mail_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='queuepicture',
            name='mail_subject',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='queuepicture',
            name='suppressed',
            field=models.BooleanField(default=False),
        ),
    ]
