# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-16 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0056_auto_20180816_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuepicture',
            name='mail_from_address',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='queuepicture',
            name='mail_from_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='queuepicture',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presto.CourseStudent'),
        ),
    ]
