# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-16 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0057_auto_20180816_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture_queue_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='picture_queue_strict',
            field=models.BooleanField(default=False),
        ),
    ]
