# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-18 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0058_auto_20180816_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuepicture',
            name='sender',
        ),
        migrations.AddField(
            model_name='queuepicture',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presto.Course'),
        ),
    ]
