# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-22 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import presto.models


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0059_auto_20180818_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemappraisal',
            name='options',
        ),
        migrations.AlterField(
            model_name='estafette',
            name='upload_dir',
            field=models.CharField(default=presto.models.relay_dir_name, max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='appraisal',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.DeleteModel(
            name='AppraisalOption',
        ),
        migrations.DeleteModel(
            name='ItemAppraisal',
        ),
    ]
