# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-12 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import presto.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presto', '0060_auto_20180822_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefereeExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_description', models.TextField(blank=True, default='')),
                ('upload_file', models.FileField(upload_to=presto.models.template_dir)),
                ('time_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_text', models.TextField(blank=True, default='')),
                ('review_grade', models.IntegerField(default=0)),
                ('appeal_text', models.TextField(blank=True, default='')),
                ('best_answers', models.CharField(max_length=10)),
                ('estafette_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presto.EstafetteLeg')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rx_editor', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courseestafette',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estafettetemplate',
            name='upload_dir',
            field=models.CharField(default=presto.models.template_dir_name, max_length=34, unique=True),
        ),
    ]
