# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-14 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0062_auto_20180912_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofacknowledgement',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presto.Participant'),
        ),
    ]
