# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-16 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0063_letterofacknowledgement_participant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phrase',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='language',
        ),
        migrations.DeleteModel(
            name='Phrase',
        ),
    ]
