# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-20 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('presto', '0066_courseestafette_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseestafette',
            name='time_chart_update',
            field=models.DateTimeField(default=datetime.datetime(2000, 12, 31, 23, 0, tzinfo=utc)),
        ),
    ]
